"""Initial tables

Revision ID: 6bbca5381bce
Revises: 
Create Date: 2026-01-02 21:32:46.809782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbca5381bce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('test_cases', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('challenges_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('challenges_pkey'))
    )
    op.create_index(op.f('ix_challenges_title'), 'challenges', ['title'], unique=False)
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    # ### end Alembic commands ###
